name: Struct
author: michael
category: Native
tags: [ruby, struct, c, structure, primitive]
current: '0.2.4'
docs: 'http://github.com/michaelficarra/MooTools-Struct/blob/master/README.md'
demo: 'http://jsfiddle.net/MGYsZ/0/'
